function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
}

function imageMarkup(label, path) {
  return path ? `<figure><figcaption>${escapeHtml(label)}</figcaption><img loading="lazy" src="${escapeHtml(path)}" alt="${escapeHtml(label)}"></figure>` : "";
}

export function renderHtml(report) {
  const rows = report.clusters.map((cluster) => {
    const samples = cluster.items.map((item) => `<details><summary>${escapeHtml(item.id)}: ${item.diffRatio.toFixed(4)}${item.selector ? ` - ${escapeHtml(item.selector)}` : ""}</summary><p>${escapeHtml(item.domSummary || "No DOM summary supplied.")}</p><section class="images">${imageMarkup("Baseline", item.baseline)}${imageMarkup("Actual", item.actual)}${imageMarkup("Diff", item.diff)}</section></details>`).join("");
    return `<article class="cluster severity-${cluster.severity}"><header><span class="badge">${escapeHtml(cluster.severity)}</span><h2>${escapeHtml(cluster.page)} / ${escapeHtml(cluster.component)}</h2><p>${escapeHtml(cluster.region)} | ${cluster.count} capture(s) | max ${cluster.maxDiffRatio.toFixed(4)}</p></header><p><strong>Likely cause:</strong> ${escapeHtml(cluster.likelyCause)}</p>${cluster.selectors.length ? `<p><strong>Selectors:</strong> ${cluster.selectors.map(escapeHtml).join(", ")}</p>` : ""}${samples}</article>`;
  }).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual Regression Triage</title><style>:root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f7f9fc}body{max-width:1100px;margin:0 auto;padding:32px 20px}header{border-bottom:1px solid #dbe2ec;padding-bottom:18px}.summary{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:12px;margin:24px 0}.metric,.cluster{background:#fff;border:1px solid #dbe2ec;border-radius:8px;padding:16px}.metric strong{font-size:1.5rem;display:block}.cluster{margin:16px 0;border-left-width:5px}.severity-critical{border-left-color:#c62828}.severity-high{border-left-color:#e65100}.severity-medium{border-left-color:#b8860b}.severity-low{border-left-color:#2563eb}.badge{text-transform:uppercase;font-size:.75rem;font-weight:700}.cluster h2{margin:.25rem 0}.cluster p{color:#44546a}.images{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}.images figure{margin:0;max-width:300px}.images img{width:100%;border:1px solid #dbe2ec}details{border-top:1px solid #e8edf3;padding:12px 0}summary{cursor:pointer;font-weight:600}@media(max-width:620px){.summary{grid-template-columns:repeat(2,1fr)}}</style></head><body><header><h1>Visual Regression Triage</h1><p>Source: <code>${escapeHtml(report.source)}</code> | Threshold: <code>${report.threshold}</code> | Generated: ${escapeHtml(report.generatedAt)}</p></header><section class="summary"><div class="metric"><strong>${report.summary.totalDiffs}</strong>Total diffs</div><div class="metric"><strong>${report.summary.triagedDiffs}</strong>Triaged diffs</div><div class="metric"><strong>${report.summary.clusters}</strong>Clusters</div><div class="metric"><strong>${report.summary.needsReview ? "Review" : "Clear"}</strong>Decision</div></section><main>${rows || "<p>No diffs exceeded the configured threshold.</p>"}</main></body></html>`;
}
